apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-proxy
data:
  nginx.conf: |
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;

      proxy_headers_hash_max_size     1024;  
      proxy_headers_hash_bucket_size  128;  

      sendfile on;
      keepalive_timeout  65;

      server {
        listen       80;
        server_name  localhost;

        # ------------------
        # SUPERVISOR
        # ------------------
        location = /supervisor {
          return 301 /supervisor/;
        }
        location ^~ /supervisor/ {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_x_host;
          proxy_set_header X-NginX-Proxy true;

          proxy_pass http://127.0.0.1:9091/;
          proxy_redirect off;
          proxy_buffering off;

          proxy_set_header Host $host;  
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
        # ------------------
        # SELKIES-GSTREAMER - APP
        # ------------------
        location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_x_host;
          proxy_set_header X-NginX-Proxy true;

          proxy_pass http://127.0.0.1:8080/;
          proxy_redirect off;
          proxy_buffering off;

          proxy_set_header Host $host;  
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
        # ------------------
        # SELKIES-GSTREAMER - PROMETHEUS 
        # ------------------
        location = /metrics {
          return 301 /metrics/;
        }
        location ^~ /metrics/ {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_x_host;
          proxy_set_header X-NginX-Proxy true;

          proxy_pass http://127.0.0.1:9090/;
          proxy_redirect off;
          proxy_buffering off;

          proxy_set_header Host $host;  
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }
    }
